package com.example.w1761353;

import androidx.appcompat.app.AppCompatActivity;

import android.annotation.SuppressLint;
import android.content.Intent;
import android.os.Bundle;
import android.os.CountDownTimer;
import android.util.Log;

import android.content.res.TypedArray;

import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.Spinner;
import android.widget.TextView;

public class IdentifyCarMakeGameActivity extends AppCompatActivity implements AdapterView.OnItemSelectedListener {

    //---------------------- Initializing constant variables ----------------------//
    private static final String LOG_TAG = IdentifyCarMakeGameActivity.class.getSimpleName();

    //---------------------- Declaring instance variables ----------------------//
    private int randomNumber;
    private Spinner spinner;
    private Button identifyButton;

    public int time = 20;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_identify_car_make);

        Intent intent = getIntent();
        boolean switchTimer = intent.getBooleanExtra(MainActivity.EXTRA_MESSAGE,false);

        if(switchTimer){
            timer();
        }

        identifyButton = findViewById(R.id.identifyCarMakeAndNext_button); //Assigning the identify button identified by its id

        displayRandomCarImage();
        displayCarMakesBySpinner();
    }

    //------ Method used to display a unique random image when every time the activity started and the next button is clicked ------//
    public void displayRandomCarImage(){
        TypedArray carImages = getResources().obtainTypedArray(R.array.carImages); //Assigning array of values retrieved from an array initialized in Resources
        ImageView imageView = findViewById(R.id.identifyCarMake_imageView); //Assigning an image view identified by its id

        randomNumber = BoomerService.getRandomNumber(); //Initializing a random number generated by using the getRandomNumber() method in BoomerService class
        Log.d(LOG_TAG,"GENERATED RANDOM NUMBER: "+randomNumber);

        /*Setting the content of the image view by selecting the array element randomly and retrieving its id;
         *defValue will return when the retrieved value is not a resource*/
        imageView.setBackgroundResource(carImages.getResourceId(randomNumber, 1));

        carImages.recycle(); //Used to recycle the TypedArray, to be re-used by a later caller
    }

    //------------ Method used to display a spinner to select a car make ------------//
    public void displayCarMakesBySpinner(){
        spinner = findViewById(R.id.carMakeNames_spinner); //Assigning a spinner identified by its id
        if (spinner != null) {
            spinner.setOnItemSelectedListener(this);
        }

        //Create ArrayAdapter using the string array and 'simple_spinner_item' layout used to provide a layout for each spinner item
        ArrayAdapter<CharSequence> carMakeNamesAdapter
                = ArrayAdapter.createFromResource(this, R.array.car_make_names, android.R.layout.simple_spinner_item);

        //'simple_spinner_dropdown_item' layout is used display the spinner items when the list of choices appear
        carMakeNamesAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);

        //Apply the adapter to the spinner
        if (spinner != null) {
            spinner.setAdapter(carMakeNamesAdapter);
        }
    }

    //-- Method used to check the car make selected from the spinner is correct or not according to the displayed random image by clicking the identify button --//
    public void launch_next_game(View view) {
        Log.d(LOG_TAG,"SELECTED ITEM FROM SPINNER: " + spinner.getSelectedItem());

        //Checking whether the selected spinner item is correct according to the generated random number by checking the index range corresponding to the car makes//
        if (randomNumber<=4){
            if(spinner.getSelectedItem().equals("Audi")) {
                BoomerService.displayMessage("OK", "#47d147", "CORRECT !", "", view);
            }
            else {
                BoomerService.displayMessage("OK", "#C54024", "WRONG !", "Audi", view);
            }
        }
        else if(randomNumber==5 || randomNumber<=9){
            if(spinner.getSelectedItem().equals("Benz")) {
                BoomerService.displayMessage("OK", "#47d147", "CORRECT !", "", view);
            }
            else {
                BoomerService.displayMessage("OK", "#C54024", "WRONG !", "Benz", view);
            }
        }
        else if(randomNumber==10 || randomNumber<=14){
            if(spinner.getSelectedItem().equals("BMW")) {
                BoomerService.displayMessage("OK", "#47d147", "CORRECT !", "", view);
            }
            else {
                BoomerService.displayMessage("OK", "#C54024", "WRONG !", "BMW", view);
            }
        }
        else if(randomNumber==15 || randomNumber<=19){
            if(spinner.getSelectedItem().equals("Lamborghini")) {
                BoomerService.displayMessage("OK", "#47d147", "CORRECT !", "", view);
            }
            else {
                BoomerService.displayMessage("OK", "#C54024", "WRONG !", "Lamborghini", view);
            }
        }
        else if(randomNumber==20 || randomNumber<=24){
            if(spinner.getSelectedItem().equals("Mini")) {
                BoomerService.displayMessage("OK", "#47d147", "CORRECT !", "", view);
            }
            else {
                BoomerService.displayMessage("OK", "#C54024", "WRONG !", "Mini", view);
            }
        }
        else if(randomNumber==25 || randomNumber<=29){
            if(spinner.getSelectedItem().equals("Porsche")) {
                BoomerService.displayMessage("OK", "#47d147", "CORRECT !", "", view);
            }
            else {
                BoomerService.displayMessage("OK", "#C54024", "WRONG !", "Porsche", view);
            }
        }
        identifyButton.setText(R.string.change_button_text_next); //Setting the button text to "Next" after checking the accuracy of the selected spinner item
        identifyButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                refresh();
            }
        });
    }

    //--- Method used to display a new random image and a play round by starting the activity again ---//
    public void refresh(){
        Intent intent = getIntent(); //Receiving the data which represents to start the activity from the previous activity
        finish(); //Finishing the activity started by the previous activity
        startActivity(intent); //Starting a new activity
    }

    public void timer(){
        TextView textTimer = (TextView)findViewById(R.id.carMake_timer);
        new CountDownTimer(20000, 1000) {

            @SuppressLint("SetTextI18n")
            public void onTick(long millisUntilFinished) {
                textTimer.setText(checkDigit(time));
                time--;
            }

            @SuppressLint("SetTextI18n")
            public void onFinish() {
                textTimer.setText("00");
                launch_next_game(findViewById(R.id.identifyCarMakeAndNext_button).getRootView());
            }

        }.start();
    }

    public String checkDigit(int number) {
        return number <= 9 ? "0" + number : String.valueOf(number);
    }

    @Override
    public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {

    }

    @Override
    public void onNothingSelected(AdapterView<?> parent) {

    }
}